package com.mcu.model

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.mcu.configuration.DynamoDbConfig
import java.time.LocalDateTime

@DynamoDBTable(tableName = "Comment")
class Comment {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id : String? = null
    @DynamoDBAttribute
    lateinit var userId : String
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "Comment-boardId-regist")
    lateinit var boardId : String
    @DynamoDBAttribute
    var content : String = ""
    var nickname : String? = null
    @DynamoDBTypeConverted(converter = DynamoDbConfig.LocalDateTimeConverter::class)
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "Comment-boardId-regist")
    var regist : LocalDateTime? = LocalDateTime.now()
    var formattedRegist : String? = null
}

@DynamoDBTable(tableName = "DeletedComment")
class DeletedComment() {
    constructor(comment : Comment) : this() {
        this.id = comment.id
        this.userId = comment.userId
        this.boardId = comment.boardId
        this.regist = comment.regist
    }
    @DynamoDBHashKey
    var id : String? = null
    @DynamoDBAttribute
    lateinit var userId : String
    @DynamoDBAttribute
    lateinit var boardId : String
    @DynamoDBAttribute
    var content : String = ""
    @DynamoDBTypeConverted(converter = DynamoDbConfig.LocalDateTimeConverter::class)
    @DynamoDBAttribute
    var regist : LocalDateTime? = LocalDateTime.now()
    @DynamoDBTypeConverted(converter = DynamoDbConfig.LocalDateTimeConverter::class)
    @DynamoDBAttribute
    var deleteDate : LocalDateTime? = null
    @DynamoDBAttribute
    var expire : Long? = null
}