package com.mcu.model

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.mcu.configuration.DynamoDbConfig
import java.time.LocalDateTime

@DynamoDBTable(tableName = "History")
class DynamoHistory {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id : String? = null
    @DynamoDBAttribute
    var priority : String = ""              // 히스토리 타입 혹은 중요도
    @DynamoDBAttribute
    var userId : String = "admin"       // 기본값으로 admin
    @DynamoDBAttribute
    var ip : String = ""                // 해당 히스토리 발생 ip
    @DynamoDBAttribute
    var detail : String = ""            // 히스토리 메시지
    @DynamoDBTypeConverted(converter = DynamoDbConfig.LocalDateTimeConverter::class)
    @DynamoDBAttribute
    var date : LocalDateTime? = null    // 해당 히스토리 생성 시간
    @DynamoDBAttribute
    var expire : Long? = null
    companion object {
        const val SYSTEM = "SYSTEM"
        const val USER_REQUEST = "USER_REQUEST"
        const val RULE_OVER = "RULE_OVER"
        const val ERROR = "ERROR"
    }
}