package com.mcu.model

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.mcu.configuration.DynamoDbConfig
import java.time.LocalDateTime

@DynamoDBTable(tableName = "History")
class History {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id : String? = null
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "History-priority-date")
    var priority : String = ""              // 히스토리 타입 혹은 중요도
    @DynamoDBAttribute
    var userId : String = "admin"       // 기본값으로 admin
    @DynamoDBAttribute
    var ip : String = ""                // 해당 히스토리 발생 ip
    @DynamoDBAttribute
    var detail : String = ""            // 히스토리 메시지
    @DynamoDBTypeConverted(converter = DynamoDbConfig.LocalDateTimeConverter::class)
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "History-priority-date")
    var date : LocalDateTime? = null    // 해당 히스토리 생성 시간
    @DynamoDBAttribute
    var expire : Long? = null
}

enum class HistoryPriority(val msgName : String) {
    NEW_BOARD("신규글"),
    SYSTEM("시스템메시지"),
    USER_REQUEST("사용자요청"),
    USER_SIGN("신규유저"),
    RULE_OVER("위반사항"),
    ERROR("에러")
}